name: Publish to GitHub Packages

on:
  push:
    tags:
      - "@mikesprague/*@*"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 24
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NX_TUI: false

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: 👷  Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🏗️  Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@mikesprague"

      - name: ⬆️  Update npm and install dependencies
        run: npm install

      - name: 📦  Build packages
        run: npm run build

      - name: ✅  Run tests and linters
        run: npm test

      - name: 🚀  Publish packages
        run: npx nx release publish
